mitigator_log_file: "log/mitigator.log"
email_template: "smtp_template.txt"

ip_block_threshold: 200

connection_setting:
  default_smtp:
    smtp_server: "smtp.gmail.com"
    port: 465
    sender_email: ""
    application_token: ""
    
    client_email_address:
      - ""

  default_scp:
    target_ip:
      - ""
    store_file_path: "/tmp/"

  default_http:
    url:
      - "127.0.0.1:8080"

devices_profile_path:
  device-a: "device_profile/device-a.yaml"
  device-b: "device_profile/device-b.yaml"
  IoT-Test: "device_profile/IoT-Test.yaml"